"""MT-1 (wave-6 P-211): route coverage + OpenAPI drift.

1. `docs/reference/openapi.json` (generated by scripts/gen_openapi.py) equals
   the live app's schema: adding/removing/changing a route or a wire model
   without regenerating is red.
2. With MCPR_ENFORCE_ROUTE_COVERAGE=1, every OpenAPI (method, path) was
   requested by some test through TestClient and got at least one 2xx
   (outside route_hits.NEGATIVE_ONLY). Named test_zz_* so it runs after the
   rest in a single-process run; under xdist the controller enforces the
   same check at sessionfinish (tests/support/route_hits.py).
"""

from __future__ import annotations

import importlib.util
import json
import os
from pathlib import Path
from types import ModuleType

import pytest

from mcprouter.settings import Settings
from tests.support import route_hits

from .conftest import requires_db

ROOT = Path(__file__).resolve().parents[1]


def _gen_openapi() -> ModuleType:
    spec = importlib.util.spec_from_file_location(
        "gen_openapi", ROOT / "scripts" / "gen_openapi.py"
    )
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@requires_db
def test_openapi_snapshot_is_current(settings: Settings) -> None:
    gen = _gen_openapi()
    live = gen.render(gen.build_spec(settings.database_url))
    committed = route_hits.SNAPSHOT.read_text()
    if live != committed:
        live_routes = route_hits.snapshot_routes(json.loads(live))
        snap_routes = route_hits.snapshot_routes(json.loads(committed))
        pytest.fail(
            "docs/reference/openapi.json is stale; run scripts/gen_openapi.py "
            f"(added={sorted(live_routes - snap_routes)} removed={sorted(snap_routes - live_routes)})"
        )


def test_coverage_check_flags_missing_and_negative_routes() -> None:
    """The checker itself (no DB): never requested, never 2xx, stale allowlist."""
    routes = {("GET", "/a"), ("POST", "/b"), ("GET", "/c")}
    hits = {("GET", "/a"): {200}, ("POST", "/b"): {401, 422}}
    problems = route_hits.coverage_failures(hits, routes, negative_only={("GET", "/gone"): "x"})
    assert problems == [
        "never requested: GET /c",
        "never 2xx: POST /b (codes [401, 422])",
        "NEGATIVE_ONLY lists a route that no longer exists: ('GET', '/gone')",
    ]
    assert route_hits.coverage_failures(hits, routes - {("GET", "/c")}, {("POST", "/b"): "r"}) == []


def test_every_route_is_requested_and_succeeds() -> None:
    if not route_hits.enforced():
        pytest.skip(f"set {route_hits.ENFORCE_ENV}=1 on a full run to enforce route coverage")
    if os.environ.get("PYTEST_XDIST_WORKER"):
        pytest.skip("under xdist the controller enforces this at sessionfinish")
    routes = route_hits.snapshot_routes()
    problems = route_hits.coverage_failures(route_hits.HITS, routes)
    assert not problems, route_hits.summary(route_hits.HITS, routes) + "\n" + "\n".join(problems)
