/**
 * The backend's OpenAPI document (docs/reference/openapi.json, committed by the
 * backend and regenerated by scripts/gen_openapi.py) as a test oracle: every request
 * the UI makes in a test is checked against it (method + path, query keys, JSON body
 * keys), and meta.test.ts checks the client's static request table and the response
 * fields the UI's types rely on.
 */
interface Schema {
  $ref?: string;
  type?: string;
  properties?: Record<string, Schema>;
  items?: Schema;
  anyOf?: Schema[];
  oneOf?: Schema[];
  allOf?: Schema[];
  additionalProperties?: boolean | Schema;
}
interface Parameter {
  name: string;
  in: string;
}
interface Operation {
  parameters?: Parameter[];
  requestBody?: { content?: Record<string, { schema?: Schema }> };
  responses?: Record<string, { content?: Record<string, { schema?: Schema }> }>;
}
export interface OpenApi {
  paths: Record<string, Record<string, Operation>>;
  components?: { schemas?: Record<string, Schema> };
}

const found = import.meta.glob<OpenApi>("../../../docs/reference/openapi.json", { eager: true, import: "default" });
/** Undefined when the file is missing; meta.test.ts fails loudly in that case. */
export const OPENAPI: OpenApi | undefined = Object.values(found)[0];

const PARAM = /\{[^}]+\}/g;
function templateRegex(template: string): RegExp {
  const parts = template.split(PARAM).map((p) => p.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"));
  const names = template.match(PARAM) ?? [];
  // `{path}` (skill resources) may contain slashes; other params are one segment.
  return new RegExp(`^${parts.map((p, i) => p + (i < names.length ? (names[i] === "{path}" ? ".+" : "[^/]+") : "")).join("")}$`);
}

/** The OpenAPI operation for a concrete method + path; literal segments win over params. */
export function findOperation(spec: OpenApi, method: string, path: string): { template: string; op: Operation } | undefined {
  let best: { template: string; op: Operation; literals: number } | undefined;
  for (const [template, ops] of Object.entries(spec.paths)) {
    const op = ops[method.toLowerCase()];
    if (!op || !templateRegex(template).test(path)) continue;
    const literals = template.split("/").filter((s) => s && !s.startsWith("{")).length;
    if (!best || literals > best.literals) best = { template, op, literals };
  }
  return best && { template: best.template, op: best.op };
}

function resolve(spec: OpenApi, s: Schema | undefined): Schema | undefined {
  let cur = s;
  for (let i = 0; cur?.$ref && i < 20; i++) cur = spec.components?.schemas?.[cur.$ref.split("/").pop()!];
  return cur;
}

/**
 * Property names an object schema declares, or null when any key is accepted
 * (free-form dict, or no schema). anyOf/oneOf/allOf members are unioned.
 */
export function objectKeys(spec: OpenApi, s: Schema | undefined): Set<string> | null {
  const r = resolve(spec, s);
  if (!r) return null;
  const union = r.anyOf ?? r.oneOf ?? r.allOf;
  if (union) {
    const out = new Set<string>();
    for (const m of union) {
      const mr = resolve(spec, m);
      if (mr?.type === "null") continue;
      const k = objectKeys(spec, m);
      if (k === null) return null;
      k.forEach((x) => out.add(x));
    }
    return out;
  }
  if (!r.properties || r.additionalProperties === true || typeof r.additionalProperties === "object") return null;
  return new Set(Object.keys(r.properties));
}

/** The schema reached by following `steps` ("[]" = array items, else a property) from a response root. */
export function responseSchema(spec: OpenApi, method: string, template: string, steps: string[]): Schema | undefined {
  const op = spec.paths[template]?.[method.toLowerCase()];
  const ok = op?.responses?.["200"] ?? op?.responses?.["201"];
  let s = resolve(spec, ok?.content?.["application/json"]?.schema);
  for (const step of steps) {
    if (!s) return undefined;
    const union = s.anyOf ?? s.oneOf;
    if (union) s = resolve(spec, union.find((m) => resolve(spec, m)?.type !== "null"));
    if (!s) return undefined;
    s = resolve(spec, step === "[]" ? s.items : s.properties?.[step]);
  }
  return s;
}

/** Problems with one request against the spec: unknown route, undeclared query or body keys. */
export function requestProblems(spec: OpenApi, method: string, path: string, query: string[], body: unknown): string[] {
  const hit = findOperation(spec, method, path);
  if (!hit) return [`${method} ${path} is not an operation in docs/reference/openapi.json`];
  const out: string[] = [];
  const declared = new Set((hit.op.parameters ?? []).filter((p) => p.in === "query").map((p) => p.name));
  for (const k of query) if (!declared.has(k)) out.push(`${method} ${hit.template}: query key "${k}" is not declared (declared: ${[...declared].join(", ") || "none"})`);
  if (body !== undefined) {
    const schema = hit.op.requestBody?.content?.["application/json"]?.schema;
    if (!schema) out.push(`${method} ${hit.template} takes no JSON body, but one was sent`);
    else if (body !== null && typeof body === "object" && !Array.isArray(body)) {
      const keys = objectKeys(spec, schema);
      if (keys) for (const k of Object.keys(body)) if (!keys.has(k)) out.push(`${method} ${hit.template}: body key "${k}" is not in the request schema (${[...keys].join(", ")})`);
    }
  }
  return out;
}
