"""Regenerate docs/reference/api.md from the live app (wave-6 P-212).

    MCPR_DATABASE_URL=postgresql+psycopg://... .venv/bin/python scripts/gen_api_docs.py

One row per OpenAPI (method, path): auth class (from the MT-2 classifier in
tests/support/auth_matrix.py), tag, summary and the first docstring line.
`--check` exits 1 when the committed file is stale; tests/test_api_docs.py
fails on drift.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "reference" / "api.md"

HEADER = """# REST API reference

<!-- GENERATED by scripts/gen_api_docs.py from the live app; do not edit by hand. -->

Every route of the MCP Router REST API, generated from the app's route table
(machine-readable schema: [`openapi.json`](openapi.json); interactive docs at
`/docs` on a running router). The MCP endpoint `/mcp` and `/metrics` are not
REST routes and are not listed. `/metrics` (Prometheus) needs
`Authorization: Bearer $MCPR_ADMIN_TOKEN` whenever an admin token is configured
(missing or wrong -> 401) and is open when none is (dev / loopback-only).

Auth classes (enforced by `tests/test_auth_matrix.py`):

| class | credential |
|---|---|
| ADMIN | `Authorization: Bearer $MCPR_ADMIN_TOKEN`. Missing, wrong or an agent key -> 401; no admin token configured outside dev mode -> 403. |
| AGENT | An agent API key. Missing or invalid -> 401. |
| EITHER | An agent key acts as itself; the admin token must name `agentId` and acts as that agent under its policy (feedback: admin = human feedback). Missing or invalid -> 401. |
| PUBLIC | None. |

Request bodies are limited to 1 MiB (413). Validation errors are 422 with
`{"detail": [{"loc", "msg", "type"}]}` and never echo the submitted input.
"""


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def build(database_url: str | None = None) -> str:
    sys.path.insert(0, str(ROOT))  # tests.support is repo tooling, not a package dep
    from tests.support.auth_matrix import api_routes, classify

    from mcprouter.api.app import create_app
    from mcprouter.settings import Settings

    url = database_url or Settings.from_env().database_url
    app = create_app(Settings(database_url=url), env={"MCPR_ADMIN_TOKEN": "x" * 40})
    ops: dict[str, Any] = app.openapi()["paths"]
    by_tag: dict[str, list[str]] = {}
    for r in api_routes(app):
        op = ops[r.path][r.method.lower()]
        tag = (op.get("tags") or ["other"])[0]
        desc = (op.get("description") or "").strip().splitlines()
        row = (
            f"| `{r.method}` | `{r.path}` | {classify(r) or 'UNCLASSIFIED'} | "
            f"{_cell(op.get('summary', ''))} | {_cell(desc[0] if desc else '')} |"
        )
        by_tag.setdefault(tag, []).append(row)
    parts = [HEADER]
    for tag in sorted(by_tag):
        parts.append(
            f"\n## {tag}\n\n| method | path | auth | summary | description |\n|---|---|---|---|---|"
        )
        parts.extend(by_tag[tag])
    total = sum(len(v) for v in by_tag.values())
    parts.append(f"\n{total} routes.\n")
    return "\n".join(parts)


def main(argv: list[str]) -> int:
    text = build()
    if "--check" in argv:
        if (OUT.read_text() if OUT.is_file() else "") != text:
            print(f"{OUT.relative_to(ROOT)} is stale; run scripts/gen_api_docs.py", file=sys.stderr)
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
